exports.seed = async function (knex) {
  await knex("users").del();
  await knex("users").insert([
    {
      user_id: 1,
      first_name: "Sabrine",
      last_name: "Dhaliwal",
      username: "SabrineD",
      email: "sabrine@example.com",
      belt_rank: "white belt - 1 stripe",
      belt_rank_id: 3,
      club_name: "matcraft",
      club_id: 1,
      bio: "Just starting out and this is tough!",
      image: "",
    },
    {
      user_id: 2,
      first_name: "John",
      last_name: "Doe",
      username: "johndoe",
      email: "john@example.com",
      belt_rank: "black belt - no stripe",
      belt_rank_id: 22,
      club_name: "matcraft",
      club_id:1,
      bio: "I have been practicing martial arts for 10 years and love competing in tournaments.",
      image: "",
    },
    {
      user_id: 3,
      first_name: "Jane",
      last_name: "Smith",
      username: "JaneDoeBJJnewbie",
      email: "jane@example.com",
      belt_rank: "brown belt - no stripe",
      belt_rank_id: 17,
      club_name: "Lions MMA",
      club_id: 2,
      bio: "I started training in karate at a young age and have a passion for teaching self-defense.",
      image: "",
    },
    {
      user_id: 4,
      first_name: "Mike",
      last_name: "Johnson",
      username: "MickyJ",
      email: "mike@example.com",
      belt_rank: "blue belt - 2 stripe",
      belt_rank_id: 9,
      club_name: "Lions MMA",
      club_id: 2,
      bio: "I'm a Brazilian Jiu-Jitsu enthusiast and have won several championships in my weight class.",
      image: "",
    },
  ]);
};
